packages:
  - base
  - base-devel
  - zsh
  - age
  - pass
  - qrencode
  - autorandr
  - git
  - i3
  - alacritty
  - go
  - docker
  - tmux
  - thunar
  - gvfs
  - thunar-volman
  - vagrant
  - pulseaudio
  - scrot
  - xfce4-screenshooter
  - unzip
  - baobab
  - bluez
  - bluez-utils
  - alsa-plugins
  - alsa-utils
  - dunst
  - pavucontrol
  - neovim
  - lazygit
  - ripgrep
  - powerline
  - powerline-common
  - rofi
  - scrot
  - vlc
  - wget
  - xorg
  - xorg-xinit
  - stow
  - networkmanager
  - network-manager-applet
  - ttf-roboto-mono
  - npm
  - ttf-sourcecodepro-nerd
  - ttf-roboto-mono-nerd
  - picom
  - feh
  - htop
  - synapse
  - fzf

aur_packages:
  - polybar
  - ttf-font-awesome
  - noto-fonts-emoji
  - corrupter-git
  - neovim-symlinks
